# Generated by Django 4.1.4 on 2023-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_likedproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
