# Generated by Django 4.1.4 on 2023-03-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_product_features"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LikedProducts",
        ),
    ]
